// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAllAppointments = `-- name: CountAllAppointments :one
SELECT COUNT(*) FROM appointments 
WHERE deleted_at IS NULL
`

func (q *Queries) CountAllAppointments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllAppointments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppointmentsByDate = `-- name: CountAppointmentsByDate :one
SELECT COUNT(*) FROM appointments 
WHERE appointment_date = $1 
  AND status IN ('pending', 'completed') 
  AND deleted_at IS NULL
`

func (q *Queries) CountAppointmentsByDate(ctx context.Context, appointmentDate time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppointmentsByDate, appointmentDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAppointments = `-- name: CountUserAppointments :one
SELECT COUNT(*) FROM appointments 
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUserAppointments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserAppointments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    user_id,
    appointment_date,
    status,
    notes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at
`

type CreateAppointmentParams struct {
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.UserID,
		arg.AppointmentDate,
		arg.Status,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :one
UPDATE appointments 
SET deleted_at = now() 
WHERE id = $1 AND deleted_at IS NULL 
RETURNING id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, deleteAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllAppointments = `-- name: GetAllAppointments :many
SELECT 
    a.id,
    a.user_id,
    a.appointment_date,
    a.status,
    a.notes,
    a.created_at,
    a.updated_at,
    a.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone
FROM appointments a
JOIN users u ON a.user_id = u.id
WHERE a.deleted_at IS NULL
ORDER BY a.appointment_date DESC, a.created_at DESC
LIMIT $2 OFFSET $1
`

type GetAllAppointmentsParams struct {
	OffsetCount int32
	LimitCount  int32
}

type GetAllAppointmentsRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	UserName        string
	UserLastname    string
	UserPhone       string
}

func (q *Queries) GetAllAppointments(ctx context.Context, arg GetAllAppointmentsParams) ([]GetAllAppointmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAppointments, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAppointmentsRow
	for rows.Next() {
		var i GetAllAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppointmentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserLastname,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointment = `-- name: GetAppointment :one
SELECT id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at FROM appointments 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAppointment(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointment, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAppointmentStats = `-- name: GetAppointmentStats :one
SELECT 
    COUNT(*) as total_appointments,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_appointments,
    COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_appointments,
    COUNT(CASE WHEN status = 'cancelled' THEN 1 END) as cancelled_appointments
FROM appointments 
WHERE deleted_at IS NULL
`

type GetAppointmentStatsRow struct {
	TotalAppointments     int64
	PendingAppointments   int64
	CompletedAppointments int64
	CancelledAppointments int64
}

func (q *Queries) GetAppointmentStats(ctx context.Context) (GetAppointmentStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentStats)
	var i GetAppointmentStatsRow
	err := row.Scan(
		&i.TotalAppointments,
		&i.PendingAppointments,
		&i.CompletedAppointments,
		&i.CancelledAppointments,
	)
	return i, err
}

const getAppointmentWithUser = `-- name: GetAppointmentWithUser :one
SELECT 
    a.id,
    a.user_id,
    a.appointment_date,
    a.status,
    a.notes,
    a.created_at,
    a.updated_at,
    a.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone
FROM appointments a
JOIN users u ON a.user_id = u.id
WHERE a.id = $1 AND a.deleted_at IS NULL
`

type GetAppointmentWithUserRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	UserName        string
	UserLastname    string
	UserPhone       string
}

func (q *Queries) GetAppointmentWithUser(ctx context.Context, id uuid.UUID) (GetAppointmentWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentWithUser, id)
	var i GetAppointmentWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserName,
		&i.UserLastname,
		&i.UserPhone,
	)
	return i, err
}

const getAppointmentsByDateRange = `-- name: GetAppointmentsByDateRange :many
SELECT 
    a.id,
    a.user_id,
    a.appointment_date,
    a.status,
    a.notes,
    a.created_at,
    a.updated_at,
    a.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone
FROM appointments a
JOIN users u ON a.user_id = u.id
WHERE a.appointment_date >= $1 
  AND a.appointment_date <= $2
  AND a.deleted_at IS NULL
ORDER BY a.appointment_date ASC, a.created_at ASC
`

type GetAppointmentsByDateRangeParams struct {
	StartDate time.Time
	EndDate   time.Time
}

type GetAppointmentsByDateRangeRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	UserName        string
	UserLastname    string
	UserPhone       string
}

func (q *Queries) GetAppointmentsByDateRange(ctx context.Context, arg GetAppointmentsByDateRangeParams) ([]GetAppointmentsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAppointmentsByDateRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppointmentsByDateRangeRow
	for rows.Next() {
		var i GetAppointmentsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppointmentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserLastname,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingAppointments = `-- name: GetUpcomingAppointments :many
SELECT 
    a.id,
    a.user_id,
    a.appointment_date,
    a.status,
    a.notes,
    a.created_at,
    a.updated_at,
    a.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone
FROM appointments a
JOIN users u ON a.user_id = u.id
WHERE a.appointment_date >= CURRENT_DATE
  AND a.status = 'pending'
  AND a.deleted_at IS NULL
ORDER BY a.appointment_date ASC, a.created_at ASC
LIMIT $1
`

type GetUpcomingAppointmentsRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	UserName        string
	UserLastname    string
	UserPhone       string
}

func (q *Queries) GetUpcomingAppointments(ctx context.Context, limitCount int32) ([]GetUpcomingAppointmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingAppointments, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingAppointmentsRow
	for rows.Next() {
		var i GetUpcomingAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppointmentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserLastname,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActiveAppointment = `-- name: GetUserActiveAppointment :one
SELECT id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at FROM appointments 
WHERE user_id = $1 
  AND status IN ('pending') 
  AND appointment_date >= CURRENT_DATE
  AND deleted_at IS NULL
ORDER BY appointment_date ASC
LIMIT 1
`

func (q *Queries) GetUserActiveAppointment(ctx context.Context, userID uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getUserActiveAppointment, userID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAppointments = `-- name: GetUserAppointments :many
SELECT id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at FROM appointments 
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY appointment_date DESC
LIMIT $3 OFFSET $2
`

type GetUserAppointmentsParams struct {
	UserID      uuid.UUID
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) GetUserAppointments(ctx context.Context, arg GetUserAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, getUserAppointments, arg.UserID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppointmentDate,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET 
    appointment_date = COALESCE($1, appointment_date),
    notes = COALESCE($2, notes),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at
`

type UpdateAppointmentParams struct {
	AppointmentDate time.Time
	Notes           sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointment, arg.AppointmentDate, arg.Notes, arg.ID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET 
    status = $1,
    notes = COALESCE($2, notes),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, user_id, appointment_date, status, notes, created_at, updated_at, deleted_at
`

type UpdateAppointmentStatusParams struct {
	Status string
	Notes  sql.NullString
	ID     uuid.UUID
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointmentStatus, arg.Status, arg.Notes, arg.ID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppointmentDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
