// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: available_slots.sql

package db

import (
	"context"
	"time"
)

const activateDate = `-- name: ActivateDate :one
UPDATE available_dates
SET is_active = true,
    updated_at = now()
WHERE slot_date = $1
RETURNING id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at
`

func (q *Queries) ActivateDate(ctx context.Context, slotDate time.Time) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, activateDate, slotDate)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAvailableDates = `-- name: CountAvailableDates :one
SELECT COUNT(*) FROM available_dates 
WHERE slot_date >= $1 
  AND slot_date <= $2
  AND is_active = true
  AND current_bookings < max_capacity
`

type CountAvailableDatesParams struct {
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) CountAvailableDates(ctx context.Context, arg CountAvailableDatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAvailableDates, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAvailableDate = `-- name: CreateAvailableDate :one
INSERT INTO available_dates (
    slot_date,
    max_capacity,
    current_bookings,
    is_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at
`

type CreateAvailableDateParams struct {
	SlotDate        time.Time
	MaxCapacity     int32
	CurrentBookings int32
	IsActive        bool
}

func (q *Queries) CreateAvailableDate(ctx context.Context, arg CreateAvailableDateParams) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, createAvailableDate,
		arg.SlotDate,
		arg.MaxCapacity,
		arg.CurrentBookings,
		arg.IsActive,
	)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDate = `-- name: DeactivateDate :one
UPDATE available_dates
SET is_active = false,
    updated_at = now()
WHERE slot_date = $1
RETURNING id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at
`

func (q *Queries) DeactivateDate(ctx context.Context, slotDate time.Time) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, deactivateDate, slotDate)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAvailableDate = `-- name: DeleteAvailableDate :exec
DELETE FROM available_dates
WHERE slot_date = $1
`

func (q *Queries) DeleteAvailableDate(ctx context.Context, slotDate time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteAvailableDate, slotDate)
	return err
}

const deleteOldDates = `-- name: DeleteOldDates :exec
DELETE FROM available_dates
WHERE slot_date < $1
`

func (q *Queries) DeleteOldDates(ctx context.Context, cutoffDate time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldDates, cutoffDate)
	return err
}

const getAllAvailableDates = `-- name: GetAllAvailableDates :many
SELECT id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at FROM available_dates 
WHERE slot_date >= $1 
  AND slot_date <= $2
ORDER BY slot_date ASC
`

type GetAllAvailableDatesParams struct {
	StartDate time.Time
	EndDate   time.Time
}

// Admin/Manager queries for managing availability dates
func (q *Queries) GetAllAvailableDates(ctx context.Context, arg GetAllAvailableDatesParams) ([]AvailableDate, error) {
	rows, err := q.db.QueryContext(ctx, getAllAvailableDates, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailableDate
	for rows.Next() {
		var i AvailableDate
		if err := rows.Scan(
			&i.ID,
			&i.SlotDate,
			&i.MaxCapacity,
			&i.CurrentBookings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableDate = `-- name: GetAvailableDate :one
SELECT id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at FROM available_dates 
WHERE slot_date = $1
`

func (q *Queries) GetAvailableDate(ctx context.Context, slotDate time.Time) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, getAvailableDate, slotDate)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableDates = `-- name: GetAvailableDates :many
SELECT id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at FROM available_dates 
WHERE slot_date >= $1 
  AND slot_date <= $2
  AND is_active = true
ORDER BY slot_date ASC
`

type GetAvailableDatesParams struct {
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetAvailableDates(ctx context.Context, arg GetAvailableDatesParams) ([]AvailableDate, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableDates, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailableDate
	for rows.Next() {
		var i AvailableDate
		if err := rows.Scan(
			&i.ID,
			&i.SlotDate,
			&i.MaxCapacity,
			&i.CurrentBookings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableDatesWithCapacity = `-- name: GetAvailableDatesWithCapacity :many
SELECT id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at FROM available_dates 
WHERE slot_date >= $1 
  AND slot_date <= $2
  AND is_active = true
  AND current_bookings < max_capacity
ORDER BY slot_date ASC
`

type GetAvailableDatesWithCapacityParams struct {
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetAvailableDatesWithCapacity(ctx context.Context, arg GetAvailableDatesWithCapacityParams) ([]AvailableDate, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableDatesWithCapacity, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailableDate
	for rows.Next() {
		var i AvailableDate
		if err := rows.Scan(
			&i.ID,
			&i.SlotDate,
			&i.MaxCapacity,
			&i.CurrentBookings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDateAvailability = `-- name: GetDateAvailability :one
SELECT 
    slot_date,
    max_capacity,
    current_bookings,
    (max_capacity - current_bookings) as available_spots,
    is_active
FROM available_dates 
WHERE slot_date = $1
`

type GetDateAvailabilityRow struct {
	SlotDate        time.Time
	MaxCapacity     int32
	CurrentBookings int32
	AvailableSpots  int32
	IsActive        bool
}

func (q *Queries) GetDateAvailability(ctx context.Context, slotDate time.Time) (GetDateAvailabilityRow, error) {
	row := q.db.QueryRowContext(ctx, getDateAvailability, slotDate)
	var i GetDateAvailabilityRow
	err := row.Scan(
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.AvailableSpots,
		&i.IsActive,
	)
	return i, err
}

const updateAvailableDate = `-- name: UpdateAvailableDate :one
UPDATE available_dates
SET max_capacity = $1,
    is_active = $2,
    updated_at = now()
WHERE slot_date = $3
RETURNING id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at
`

type UpdateAvailableDateParams struct {
	MaxCapacity int32
	IsActive    bool
	SlotDate    time.Time
}

func (q *Queries) UpdateAvailableDate(ctx context.Context, arg UpdateAvailableDateParams) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, updateAvailableDate, arg.MaxCapacity, arg.IsActive, arg.SlotDate)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDateBookingCount = `-- name: UpdateDateBookingCount :one
UPDATE available_dates
SET current_bookings = $1,
    updated_at = now()
WHERE slot_date = $2
RETURNING id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at
`

type UpdateDateBookingCountParams struct {
	CurrentBookings int32
	SlotDate        time.Time
}

func (q *Queries) UpdateDateBookingCount(ctx context.Context, arg UpdateDateBookingCountParams) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, updateDateBookingCount, arg.CurrentBookings, arg.SlotDate)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAvailableDate = `-- name: UpsertAvailableDate :one
INSERT INTO available_dates (
    slot_date,
    max_capacity,
    current_bookings,
    is_active
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (slot_date) 
DO UPDATE SET 
    max_capacity = EXCLUDED.max_capacity,
    is_active = EXCLUDED.is_active,
    updated_at = now()
RETURNING id, slot_date, max_capacity, current_bookings, is_active, created_at, updated_at
`

type UpsertAvailableDateParams struct {
	SlotDate        time.Time
	MaxCapacity     int32
	CurrentBookings int32
	IsActive        bool
}

func (q *Queries) UpsertAvailableDate(ctx context.Context, arg UpsertAvailableDateParams) (AvailableDate, error) {
	row := q.db.QueryRowContext(ctx, upsertAvailableDate,
		arg.SlotDate,
		arg.MaxCapacity,
		arg.CurrentBookings,
		arg.IsActive,
	)
	var i AvailableDate
	err := row.Scan(
		&i.ID,
		&i.SlotDate,
		&i.MaxCapacity,
		&i.CurrentBookings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
