// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: communion.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAllCommunions = `-- name: CountAllCommunions :one
SELECT COUNT(*) FROM communion 
WHERE deleted_at IS NULL
`

func (q *Queries) CountAllCommunions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllCommunions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingCommunions = `-- name: CountPendingCommunions :one
SELECT COUNT(*) FROM communion 
WHERE status = 'pending' AND deleted_at IS NULL
`

func (q *Queries) CountPendingCommunions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingCommunions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommunion = `-- name: CreateCommunion :one
INSERT INTO communion (
    user_id,
    communion_date,
    status,
    requested_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, communion_date, status, requested_at, approved_at, approved_by_user_id, created_at, updated_at, deleted_at
`

type CreateCommunionParams struct {
	UserID        uuid.UUID
	CommunionDate time.Time
	Status        string
	RequestedAt   time.Time
}

func (q *Queries) CreateCommunion(ctx context.Context, arg CreateCommunionParams) (Communion, error) {
	row := q.db.QueryRowContext(ctx, createCommunion,
		arg.UserID,
		arg.CommunionDate,
		arg.Status,
		arg.RequestedAt,
	)
	var i Communion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCommunion = `-- name: DeleteCommunion :one
UPDATE communion 
SET deleted_at = now() 
WHERE id = $1 AND deleted_at IS NULL 
RETURNING id, user_id, communion_date, status, requested_at, approved_at, approved_by_user_id, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteCommunion(ctx context.Context, id uuid.UUID) (Communion, error) {
	row := q.db.QueryRowContext(ctx, deleteCommunion, id)
	var i Communion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllCommunions = `-- name: GetAllCommunions :many
SELECT 
    c.id,
    c.user_id,
    c.communion_date,
    c.status,
    c.requested_at,
    c.approved_at,
    c.approved_by_user_id,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone,
    au.name as approved_by_name,
    au.lastname as approved_by_lastname
FROM communion c
JOIN users u ON c.user_id = u.id
LEFT JOIN users au ON c.approved_by_user_id = au.id
WHERE c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $1
`

type GetAllCommunionsParams struct {
	Offset int32
	Limit  int32
}

type GetAllCommunionsRow struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	CommunionDate      time.Time
	Status             string
	RequestedAt        time.Time
	ApprovedAt         sql.NullTime
	ApprovedByUserID   uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
	UserName           string
	UserLastname       string
	UserPhone          string
	ApprovedByName     sql.NullString
	ApprovedByLastname sql.NullString
}

func (q *Queries) GetAllCommunions(ctx context.Context, arg GetAllCommunionsParams) ([]GetAllCommunionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCommunions, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCommunionsRow
	for rows.Next() {
		var i GetAllCommunionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CommunionDate,
			&i.Status,
			&i.RequestedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserLastname,
			&i.UserPhone,
			&i.ApprovedByName,
			&i.ApprovedByLastname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommunion = `-- name: GetCommunion :one
SELECT id, user_id, communion_date, status, requested_at, approved_at, approved_by_user_id, created_at, updated_at, deleted_at FROM communion 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCommunion(ctx context.Context, id uuid.UUID) (Communion, error) {
	row := q.db.QueryRowContext(ctx, getCommunion, id)
	var i Communion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommunionWithUser = `-- name: GetCommunionWithUser :one
SELECT 
    c.id,
    c.user_id,
    c.communion_date,
    c.status,
    c.requested_at,
    c.approved_at,
    c.approved_by_user_id,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone,
    au.name as approved_by_name,
    au.lastname as approved_by_lastname
FROM communion c
JOIN users u ON c.user_id = u.id
LEFT JOIN users au ON c.approved_by_user_id = au.id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCommunionWithUserRow struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	CommunionDate      time.Time
	Status             string
	RequestedAt        time.Time
	ApprovedAt         sql.NullTime
	ApprovedByUserID   uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
	UserName           string
	UserLastname       string
	UserPhone          string
	ApprovedByName     sql.NullString
	ApprovedByLastname sql.NullString
}

func (q *Queries) GetCommunionWithUser(ctx context.Context, id uuid.UUID) (GetCommunionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getCommunionWithUser, id)
	var i GetCommunionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserName,
		&i.UserLastname,
		&i.UserPhone,
		&i.ApprovedByName,
		&i.ApprovedByLastname,
	)
	return i, err
}

const getPendingCommunions = `-- name: GetPendingCommunions :many
SELECT 
    c.id,
    c.user_id,
    c.communion_date,
    c.status,
    c.requested_at,
    c.approved_at,
    c.approved_by_user_id,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    u.name as user_name,
    u.lastname as user_lastname,
    u.phone_number as user_phone
FROM communion c
JOIN users u ON c.user_id = u.id
WHERE c.status = 'pending' AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $1
`

type GetPendingCommunionsParams struct {
	Offset int32
	Limit  int32
}

type GetPendingCommunionsRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	CommunionDate    time.Time
	Status           string
	RequestedAt      time.Time
	ApprovedAt       sql.NullTime
	ApprovedByUserID uuid.NullUUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
	UserName         string
	UserLastname     string
	UserPhone        string
}

func (q *Queries) GetPendingCommunions(ctx context.Context, arg GetPendingCommunionsParams) ([]GetPendingCommunionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingCommunions, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingCommunionsRow
	for rows.Next() {
		var i GetPendingCommunionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CommunionDate,
			&i.Status,
			&i.RequestedAt,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserLastname,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCommunion = `-- name: GetUserCommunion :one
SELECT id, user_id, communion_date, status, requested_at, approved_at, approved_by_user_id, created_at, updated_at, deleted_at FROM communion 
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetUserCommunion(ctx context.Context, userID uuid.UUID) (Communion, error) {
	row := q.db.QueryRowContext(ctx, getUserCommunion, userID)
	var i Communion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserCommunionWithDetails = `-- name: GetUserCommunionWithDetails :one
SELECT 
    c.id,
    c.user_id,
    c.communion_date,
    c.status,
    c.requested_at,
    c.approved_at,
    c.approved_by_user_id,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    au.name as approved_by_name,
    au.lastname as approved_by_lastname
FROM communion c
LEFT JOIN users au ON c.approved_by_user_id = au.id
WHERE c.user_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
LIMIT 1
`

type GetUserCommunionWithDetailsRow struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	CommunionDate      time.Time
	Status             string
	RequestedAt        time.Time
	ApprovedAt         sql.NullTime
	ApprovedByUserID   uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
	ApprovedByName     sql.NullString
	ApprovedByLastname sql.NullString
}

func (q *Queries) GetUserCommunionWithDetails(ctx context.Context, userID uuid.UUID) (GetUserCommunionWithDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCommunionWithDetails, userID)
	var i GetUserCommunionWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ApprovedByName,
		&i.ApprovedByLastname,
	)
	return i, err
}

const updateCommunion = `-- name: UpdateCommunion :one
UPDATE communion
SET 
    communion_date = COALESCE($1, communion_date),
    updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, user_id, communion_date, status, requested_at, approved_at, approved_by_user_id, created_at, updated_at, deleted_at
`

type UpdateCommunionParams struct {
	CommunionDate time.Time
	ID            uuid.UUID
}

func (q *Queries) UpdateCommunion(ctx context.Context, arg UpdateCommunionParams) (Communion, error) {
	row := q.db.QueryRowContext(ctx, updateCommunion, arg.CommunionDate, arg.ID)
	var i Communion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCommunionStatus = `-- name: UpdateCommunionStatus :one
UPDATE communion
SET 
    status = $1,
    approved_at = CASE WHEN $1 IN ('approved', 'rejected') THEN now() ELSE approved_at END,
    approved_by_user_id = CASE WHEN $1 IN ('approved', 'rejected') THEN $2 ELSE approved_by_user_id END,
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, user_id, communion_date, status, requested_at, approved_at, approved_by_user_id, created_at, updated_at, deleted_at
`

type UpdateCommunionStatusParams struct {
	Status           string
	ApprovedByUserID uuid.NullUUID
	ID               uuid.UUID
}

func (q *Queries) UpdateCommunionStatus(ctx context.Context, arg UpdateCommunionStatusParams) (Communion, error) {
	row := q.db.QueryRowContext(ctx, updateCommunionStatus, arg.Status, arg.ApprovedByUserID, arg.ID)
	var i Communion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CommunionDate,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
