// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type AvailableDate struct {
	ID              uuid.UUID
	SlotDate        time.Time
	MaxCapacity     int32
	CurrentBookings int32
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Communion struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	CommunionDate    time.Time
	Status           string
	RequestedAt      time.Time
	ApprovedAt       sql.NullTime
	ApprovedByUserID uuid.NullUUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	Used      bool
}

type Question struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
	Name             string
	Lastname         string
	PhoneNumber      string
	Password         string
	TelegramID       sql.NullString
	Role             string
	JobTitle         sql.NullString
	Education        sql.NullString
	MarriageStatus   sql.NullString
	ChildrensName    []string
	Status           string
	PartnerName      sql.NullString
	TelegramVerified bool
}
