// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Status string

const (
	StatusPENDING  Status = "PENDING"
	StatusACTIVE   Status = "ACTIVE"
	StatusINACTIVE Status = "INACTIVE"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type Appointment struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AppointmentDate time.Time
	Status          string
	Notes           sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type AvailableDate struct {
	ID              uuid.UUID
	SlotDate        time.Time
	MaxCapacity     int32
	CurrentBookings int32
	IsActive        bool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Communion struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	CommunionDate    time.Time
	Status           string
	RequestedAt      time.Time
	ApprovedAt       sql.NullTime
	ApprovedByUserID uuid.NullUUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	Used      bool
}

type Question struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
	Name             string
	Lastname         string
	PhoneNumber      string
	Password         string
	TelegramID       sql.NullString
	Role             string
	JobTitle         sql.NullString
	Education        sql.NullString
	MarriageStatus   sql.NullString
	ChildrensName    []string
	Status           Status
	PartnerName      sql.NullString
	TelegramVerified bool
}
