// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    user_id, question, status
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, question, status, admin_response, responded_by, created_at, updated_at
`

type CreateQuestionParams struct {
	UserID   uuid.UUID
	Question string
	Status   string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.UserID, arg.Question, arg.Status)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Status,
		&i.AdminResponse,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions 
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const deleteQuestionByUser = `-- name: DeleteQuestionByUser :exec
DELETE FROM questions 
WHERE id = $1 AND user_id = $2 AND status = 'pending'
`

type DeleteQuestionByUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteQuestionByUser(ctx context.Context, arg DeleteQuestionByUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionByUser, arg.ID, arg.UserID)
	return err
}

const getAllQuestions = `-- name: GetAllQuestions :many
SELECT 
    q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at,
    u.name as user_name
FROM questions q
LEFT JOIN users u ON q.user_id = u.id
ORDER BY q.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllQuestionsParams struct {
	Limit  int32
	Offset int32
}

type GetAllQuestionsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserName      sql.NullString
}

func (q *Queries) GetAllQuestions(ctx context.Context, arg GetAllQuestionsParams) ([]GetAllQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQuestionsRow
	for rows.Next() {
		var i GetAllQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Status,
			&i.AdminResponse,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllQuestionsCount = `-- name: GetAllQuestionsCount :one
SELECT COUNT(*) FROM questions
`

func (q *Queries) GetAllQuestionsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllQuestionsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingQuestions = `-- name: GetPendingQuestions :many
SELECT 
    q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at,
    u.name as user_name
FROM questions q
LEFT JOIN users u ON q.user_id = u.id
WHERE q.status = 'pending'
ORDER BY q.created_at ASC
`

type GetPendingQuestionsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserName      sql.NullString
}

func (q *Queries) GetPendingQuestions(ctx context.Context) ([]GetPendingQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingQuestionsRow
	for rows.Next() {
		var i GetPendingQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Status,
			&i.AdminResponse,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestion = `-- name: GetQuestion :one
SELECT 
    q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at,
    u.name as user_name,
    r.name as responder_name
FROM questions q
LEFT JOIN users u ON q.user_id = u.id
LEFT JOIN users r ON q.responded_by = r.id
WHERE q.id = $1
`

type GetQuestionRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserName      sql.NullString
	ResponderName sql.NullString
}

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (GetQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i GetQuestionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Status,
		&i.AdminResponse,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.ResponderName,
	)
	return i, err
}

const getQuestionStats = `-- name: GetQuestionStats :one
SELECT 
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status = 'pending') as pending,
    COUNT(*) FILTER (WHERE status = 'answered') as answered,
    COUNT(*) FILTER (WHERE status = 'closed') as closed,
    COUNT(*) FILTER (WHERE status = 'cancelled') as cancelled
FROM questions
`

type GetQuestionStatsRow struct {
	Total     int64
	Pending   int64
	Answered  int64
	Closed    int64
	Cancelled int64
}

func (q *Queries) GetQuestionStats(ctx context.Context) (GetQuestionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionStats)
	var i GetQuestionStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Answered,
		&i.Closed,
		&i.Cancelled,
	)
	return i, err
}

const getQuestions = `-- name: GetQuestions :many
SELECT 
    q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at,
    CASE WHEN $6::boolean THEN u.name ELSE NULL END as user_name,
    CASE WHEN $6::boolean THEN r.name ELSE NULL END as responder_name
FROM questions q
LEFT JOIN users u ON q.user_id = u.id
LEFT JOIN users r ON q.responded_by = r.id
WHERE 
    ($1::uuid IS NULL OR q.user_id = $1) AND
    ($2::varchar IS NULL OR q.status = $2) AND
    ($3::timestamptz IS NULL OR q.created_at >= $3) AND
    ($4::timestamptz IS NULL OR q.created_at <= $4)
ORDER BY q.created_at DESC
LIMIT $5
`

type GetQuestionsParams struct {
	Column1 uuid.UUID
	Column2 string
	Column3 time.Time
	Column4 time.Time
	Limit   int32
	Column6 bool
}

type GetQuestionsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserName      interface{}
	ResponderName interface{}
}

func (q *Queries) GetQuestions(ctx context.Context, arg GetQuestionsParams) ([]GetQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuestions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsRow
	for rows.Next() {
		var i GetQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Status,
			&i.AdminResponse,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.ResponderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByStatus = `-- name: GetQuestionsByStatus :many
SELECT 
    q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at,
    u.name as user_name,
    r.name as responder_name
FROM questions q
LEFT JOIN users u ON q.user_id = u.id
LEFT JOIN users r ON q.responded_by = r.id
WHERE q.status = $1
ORDER BY q.created_at DESC
LIMIT $2 OFFSET $3
`

type GetQuestionsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

type GetQuestionsByStatusRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserName      sql.NullString
	ResponderName sql.NullString
}

func (q *Queries) GetQuestionsByStatus(ctx context.Context, arg GetQuestionsByStatusParams) ([]GetQuestionsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsByStatusRow
	for rows.Next() {
		var i GetQuestionsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Status,
			&i.AdminResponse,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.ResponderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByUser = `-- name: GetQuestionsByUser :many
SELECT q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at FROM questions q
WHERE q.user_id = $1
ORDER BY q.created_at DESC
`

func (q *Queries) GetQuestionsByUser(ctx context.Context, userID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Status,
			&i.AdminResponse,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsCount = `-- name: GetQuestionsCount :one
SELECT COUNT(*) FROM questions q
WHERE 
    ($1::uuid IS NULL OR q.user_id = $1) AND
    ($2::varchar IS NULL OR q.status = $2) AND
    ($3::timestamptz IS NULL OR q.created_at >= $3) AND
    ($4::timestamptz IS NULL OR q.created_at <= $4)
`

type GetQuestionsCountParams struct {
	Column1 uuid.UUID
	Column2 string
	Column3 time.Time
	Column4 time.Time
}

func (q *Queries) GetQuestionsCount(ctx context.Context, arg GetQuestionsCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getQuestionsCount,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuestionsPaginated = `-- name: GetQuestionsPaginated :many
SELECT 
    q.id, q.user_id, q.question, q.status, q.admin_response, q.responded_by, q.created_at, q.updated_at,
    CASE WHEN $7::boolean THEN u.name ELSE NULL END as user_name,
    CASE WHEN $7::boolean THEN r.name ELSE NULL END as responder_name
FROM questions q
LEFT JOIN users u ON q.user_id = u.id
LEFT JOIN users r ON q.responded_by = r.id
WHERE 
    ($1::uuid IS NULL OR q.user_id = $1) AND
    ($2::varchar IS NULL OR q.status = $2) AND
    ($3::timestamptz IS NULL OR q.created_at >= $3) AND
    ($4::timestamptz IS NULL OR q.created_at <= $4)
ORDER BY q.created_at DESC
LIMIT $5 OFFSET $6
`

type GetQuestionsPaginatedParams struct {
	Column1 uuid.UUID
	Column2 string
	Column3 time.Time
	Column4 time.Time
	Limit   int32
	Offset  int32
	Column7 bool
}

type GetQuestionsPaginatedRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserName      interface{}
	ResponderName interface{}
}

func (q *Queries) GetQuestionsPaginated(ctx context.Context, arg GetQuestionsPaginatedParams) ([]GetQuestionsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsPaginatedRow
	for rows.Next() {
		var i GetQuestionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Status,
			&i.AdminResponse,
			&i.RespondedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.ResponderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQuestionStats = `-- name: GetUserQuestionStats :one
SELECT 
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status = 'pending') as pending,
    COUNT(*) FILTER (WHERE status = 'answered') as answered,
    COUNT(*) FILTER (WHERE status = 'closed') as closed,
    COUNT(*) FILTER (WHERE status = 'cancelled') as cancelled
FROM questions
WHERE user_id = $1
`

type GetUserQuestionStatsRow struct {
	Total     int64
	Pending   int64
	Answered  int64
	Closed    int64
	Cancelled int64
}

func (q *Queries) GetUserQuestionStats(ctx context.Context, userID uuid.UUID) (GetUserQuestionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserQuestionStats, userID)
	var i GetUserQuestionStatsRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Answered,
		&i.Closed,
		&i.Cancelled,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions 
SET 
    question = COALESCE($2, question),
    status = COALESCE($3, status),
    admin_response = COALESCE($4, admin_response),
    responded_by = COALESCE($5, responded_by),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, question, status, admin_response, responded_by, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID
	Question      string
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.ID,
		arg.Question,
		arg.Status,
		arg.AdminResponse,
		arg.RespondedBy,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Status,
		&i.AdminResponse,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestionStatus = `-- name: UpdateQuestionStatus :one
UPDATE questions 
SET 
    status = $2,
    admin_response = $3,
    responded_by = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, question, status, admin_response, responded_by, created_at, updated_at
`

type UpdateQuestionStatusParams struct {
	ID            uuid.UUID
	Status        string
	AdminResponse sql.NullString
	RespondedBy   uuid.NullUUID
}

func (q *Queries) UpdateQuestionStatus(ctx context.Context, arg UpdateQuestionStatusParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestionStatus,
		arg.ID,
		arg.Status,
		arg.AdminResponse,
		arg.RespondedBy,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Status,
		&i.AdminResponse,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestionText = `-- name: UpdateQuestionText :one
UPDATE questions 
SET 
    question = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3 AND status = 'pending'
RETURNING id, user_id, question, status, admin_response, responded_by, created_at, updated_at
`

type UpdateQuestionTextParams struct {
	ID       uuid.UUID
	Question string
	UserID   uuid.UUID
}

func (q *Queries) UpdateQuestionText(ctx context.Context, arg UpdateQuestionTextParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestionText, arg.ID, arg.Question, arg.UserID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Status,
		&i.AdminResponse,
		&i.RespondedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
