// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const changePassword = `-- name: ChangePassword :one
UPDATE users
SET 
  password = $1,
  updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, partner_name, childrens_name, status
`

type ChangePasswordParams struct {
	Password string
	ID       uuid.UUID
}

type ChangePasswordRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	Name           string
	Lastname       string
	PhoneNumber    string
	Password       string
	TelegramID     sql.NullString
	Role           string
	JobTitle       sql.NullString
	Education      sql.NullString
	MarriageStatus sql.NullString
	PartnerName    sql.NullString
	ChildrensName  []string
	Status         Status
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) (ChangePasswordRow, error) {
	row := q.db.QueryRowContext(ctx, changePassword, arg.Password, arg.ID)
	var i ChangePasswordRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		&i.PartnerName,
		pq.Array(&i.ChildrensName),
		&i.Status,
	)
	return i, err
}

const cleanupExpiredResetTokens = `-- name: CleanupExpiredResetTokens :exec
DELETE FROM password_reset_tokens 
WHERE expires_at < NOW() OR used = TRUE
`

func (q *Queries) CleanupExpiredResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredResetTokens)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByStatus = `-- name: CountUsersByStatus :one
SELECT COUNT(*) FROM users WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUsersByStatus(ctx context.Context, status Status) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id,
    token_hash,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, token_hash, created_at, updated_at, expires_at, used
`

type CreatePasswordResetTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    lastname,
    phone_number,
    password,
    role,
    telegram_id,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified
`

type CreateUserParams struct {
	Name        string
	Lastname    string
	PhoneNumber string
	Password    string
	Role        string
	TelegramID  sql.NullString
	Status      Status
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Lastname,
		arg.PhoneNumber,
		arg.Password,
		arg.Role,
		arg.TelegramID,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users set deleted_at =now() where id=$1 AND deleted_at IS NULL RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified FROM users WHERE phone_number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const getUserByPhoneWithPassword = `-- name: GetUserByPhoneWithPassword :one
SELECT id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified FROM users 
WHERE phone_number = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhoneWithPassword(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhoneWithPassword, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified FROM users 
WHERE telegram_id = $1 AND telegram_verified = TRUE AND deleted_at IS NULL
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified FROM users WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetUsersParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Lastname,
			&i.PhoneNumber,
			&i.Password,
			&i.TelegramID,
			&i.Role,
			&i.JobTitle,
			&i.Education,
			&i.MarriageStatus,
			pq.Array(&i.ChildrensName),
			&i.Status,
			&i.PartnerName,
			&i.TelegramVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByStatus = `-- name: GetUsersByStatus :many
SELECT id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified FROM users 
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type GetUsersByStatusParams struct {
	Status      Status
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) GetUsersByStatus(ctx context.Context, arg GetUsersByStatusParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByStatus, arg.Status, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Lastname,
			&i.PhoneNumber,
			&i.Password,
			&i.TelegramID,
			&i.Role,
			&i.JobTitle,
			&i.Education,
			&i.MarriageStatus,
			pq.Array(&i.ChildrensName),
			&i.Status,
			&i.PartnerName,
			&i.TelegramVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT id, user_id, token_hash, created_at, updated_at, expires_at, used FROM password_reset_tokens 
WHERE token_hash = $1 AND used = FALSE AND expires_at > NOW()
`

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getValidPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens 
SET used = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}

const resetUserPassword = `-- name: ResetUserPassword :one
UPDATE users
SET 
  password = $1,
  updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified
`

type ResetUserPasswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, resetUserPassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const updateTelegramInfo = `-- name: UpdateTelegramInfo :one
UPDATE users
SET 
  telegram_id = $1,
  telegram_verified = $2,
  updated_at = now()
WHERE phone_number = $3 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified
`

type UpdateTelegramInfoParams struct {
	TelegramID       sql.NullString
	TelegramVerified bool
	PhoneNumber      string
}

func (q *Queries) UpdateTelegramInfo(ctx context.Context, arg UpdateTelegramInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateTelegramInfo, arg.TelegramID, arg.TelegramVerified, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  name = COALESCE(NULLIF($1, ''), name),
  lastname = COALESCE(NULLIF($2, ''), lastname),
  phone_number = COALESCE(NULLIF($3, ''), phone_number),
  job_title = $4,
  education = $5,
  marriage_status = $6,
  partner_name = $7,
  childrens_name = $8,
  telegram_id = $9,
  updated_at = now()
WHERE id = $10 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified
`

type UpdateUserParams struct {
	Name           interface{}
	Lastname       interface{}
	PhoneNumber    interface{}
	JobTitle       sql.NullString
	Education      sql.NullString
	MarriageStatus sql.NullString
	PartnerName    sql.NullString
	ChildrensName  []string
	TelegramID     sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Lastname,
		arg.PhoneNumber,
		arg.JobTitle,
		arg.Education,
		arg.MarriageStatus,
		arg.PartnerName,
		pq.Array(arg.ChildrensName),
		arg.TelegramID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET 
  status = $1,
  updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, lastname, phone_number, password, telegram_id, role, job_title, education, marriage_status, childrens_name, status, partner_name, telegram_verified
`

type UpdateUserStatusParams struct {
	Status Status
	ID     uuid.UUID
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Lastname,
		&i.PhoneNumber,
		&i.Password,
		&i.TelegramID,
		&i.Role,
		&i.JobTitle,
		&i.Education,
		&i.MarriageStatus,
		pq.Array(&i.ChildrensName),
		&i.Status,
		&i.PartnerName,
		&i.TelegramVerified,
	)
	return i, err
}

const userByPhoneExists = `-- name: UserByPhoneExists :one
SELECT count(*) FROM users where phone_number = $1 AND deleted_at IS NULL
`

func (q *Queries) UserByPhoneExists(ctx context.Context, phoneNumber string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userByPhoneExists, phoneNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}
